/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "scratch.pb-c.h"
void   scratch__puzzle__init
                     (Scratch__Puzzle         *message)
{
  static Scratch__Puzzle init_value = SCRATCH__PUZZLE__INIT;
  *message = init_value;
}
size_t scratch__puzzle__get_packed_size
                     (const Scratch__Puzzle *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__puzzle__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scratch__puzzle__pack
                     (const Scratch__Puzzle *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__puzzle__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scratch__puzzle__pack_to_buffer
                     (const Scratch__Puzzle *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__puzzle__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scratch__Puzzle *
       scratch__puzzle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scratch__Puzzle *)
     protobuf_c_message_unpack (&scratch__puzzle__descriptor,
                                allocator, len, data);
}
void   scratch__puzzle__free_unpacked
                     (Scratch__Puzzle *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__puzzle__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scratch__verifier_input__init
                     (Scratch__VerifierInput         *message)
{
  static Scratch__VerifierInput init_value = SCRATCH__VERIFIER_INPUT__INIT;
  *message = init_value;
}
size_t scratch__verifier_input__get_packed_size
                     (const Scratch__VerifierInput *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__verifier_input__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scratch__verifier_input__pack
                     (const Scratch__VerifierInput *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__verifier_input__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scratch__verifier_input__pack_to_buffer
                     (const Scratch__VerifierInput *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__verifier_input__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scratch__VerifierInput *
       scratch__verifier_input__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scratch__VerifierInput *)
     protobuf_c_message_unpack (&scratch__verifier_input__descriptor,
                                allocator, len, data);
}
void   scratch__verifier_input__free_unpacked
                     (Scratch__VerifierInput *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__verifier_input__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scratch__ticket__init
                     (Scratch__Ticket         *message)
{
  static Scratch__Ticket init_value = SCRATCH__TICKET__INIT;
  *message = init_value;
}
size_t scratch__ticket__get_packed_size
                     (const Scratch__Ticket *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__ticket__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scratch__ticket__pack
                     (const Scratch__Ticket *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__ticket__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scratch__ticket__pack_to_buffer
                     (const Scratch__Ticket *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__ticket__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scratch__Ticket *
       scratch__ticket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scratch__Ticket *)
     protobuf_c_message_unpack (&scratch__ticket__descriptor,
                                allocator, len, data);
}
void   scratch__ticket__free_unpacked
                     (Scratch__Ticket *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__ticket__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scratch__inner_witness__leafbranch__init
                     (Scratch__InnerWitness__Leafbranch         *message)
{
  static Scratch__InnerWitness__Leafbranch init_value = SCRATCH__INNER_WITNESS__LEAFBRANCH__INIT;
  *message = init_value;
}
void   scratch__inner_witness__init
                     (Scratch__InnerWitness         *message)
{
  static Scratch__InnerWitness init_value = SCRATCH__INNER_WITNESS__INIT;
  *message = init_value;
}
size_t scratch__inner_witness__get_packed_size
                     (const Scratch__InnerWitness *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__inner_witness__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scratch__inner_witness__pack
                     (const Scratch__InnerWitness *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__inner_witness__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scratch__inner_witness__pack_to_buffer
                     (const Scratch__InnerWitness *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__inner_witness__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scratch__InnerWitness *
       scratch__inner_witness__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scratch__InnerWitness *)
     protobuf_c_message_unpack (&scratch__inner_witness__descriptor,
                                allocator, len, data);
}
void   scratch__inner_witness__free_unpacked
                     (Scratch__InnerWitness *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__inner_witness__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scratch__final_witness__init
                     (Scratch__FinalWitness         *message)
{
  static Scratch__FinalWitness init_value = SCRATCH__FINAL_WITNESS__INIT;
  *message = init_value;
}
size_t scratch__final_witness__get_packed_size
                     (const Scratch__FinalWitness *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__final_witness__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scratch__final_witness__pack
                     (const Scratch__FinalWitness *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__final_witness__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scratch__final_witness__pack_to_buffer
                     (const Scratch__FinalWitness *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__final_witness__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scratch__FinalWitness *
       scratch__final_witness__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scratch__FinalWitness *)
     protobuf_c_message_unpack (&scratch__final_witness__descriptor,
                                allocator, len, data);
}
void   scratch__final_witness__free_unpacked
                     (Scratch__FinalWitness *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scratch__final_witness__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor scratch__puzzle__field_descriptors[2] =
{
  {
    "d",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__Puzzle, d),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "puzid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__Puzzle, puzid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scratch__puzzle__field_indices_by_name[] = {
  0,   /* field[0] = d */
  1,   /* field[1] = puzid */
};
static const ProtobufCIntRange scratch__puzzle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor scratch__puzzle__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "scratch.Puzzle",
  "Puzzle",
  "Scratch__Puzzle",
  "scratch",
  sizeof(Scratch__Puzzle),
  2,
  scratch__puzzle__field_descriptors,
  scratch__puzzle__field_indices_by_name,
  1,  scratch__puzzle__number_ranges,
  (ProtobufCMessageInit) scratch__puzzle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scratch__verifier_input__field_descriptors[1] =
{
  {
    "v_input",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__VerifierInput, v_input),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scratch__verifier_input__field_indices_by_name[] = {
  0,   /* field[0] = v_input */
};
static const ProtobufCIntRange scratch__verifier_input__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor scratch__verifier_input__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "scratch.VerifierInput",
  "VerifierInput",
  "Scratch__VerifierInput",
  "scratch",
  sizeof(Scratch__VerifierInput),
  1,
  scratch__verifier_input__field_descriptors,
  scratch__verifier_input__field_indices_by_name,
  1,  scratch__verifier_input__number_ranges,
  (ProtobufCMessageInit) scratch__verifier_input__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scratch__ticket__field_descriptors[3] =
{
  {
    "ciphertexts",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Scratch__Ticket, n_ciphertexts),
    PROTOBUF_C_OFFSETOF(Scratch__Ticket, ciphertexts),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hmacs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Scratch__Ticket, n_hmacs),
    PROTOBUF_C_OFFSETOF(Scratch__Ticket, hmacs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_value",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__Ticket, public_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scratch__ticket__field_indices_by_name[] = {
  0,   /* field[0] = ciphertexts */
  1,   /* field[1] = hmacs */
  2,   /* field[2] = public_value */
};
static const ProtobufCIntRange scratch__ticket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scratch__ticket__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "scratch.Ticket",
  "Ticket",
  "Scratch__Ticket",
  "scratch",
  sizeof(Scratch__Ticket),
  3,
  scratch__ticket__field_descriptors,
  scratch__ticket__field_indices_by_name,
  1,  scratch__ticket__number_ranges,
  (ProtobufCMessageInit) scratch__ticket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scratch__inner_witness__leafbranch__field_descriptors[2] =
{
  {
    "leaf",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness__Leafbranch, leaf),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "branch",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness__Leafbranch, n_branch),
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness__Leafbranch, branch),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scratch__inner_witness__leafbranch__field_indices_by_name[] = {
  1,   /* field[1] = branch */
  0,   /* field[0] = leaf */
};
static const ProtobufCIntRange scratch__inner_witness__leafbranch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor scratch__inner_witness__leafbranch__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "scratch.InnerWitness.leafbranch",
  "Leafbranch",
  "Scratch__InnerWitness__Leafbranch",
  "scratch",
  sizeof(Scratch__InnerWitness__Leafbranch),
  2,
  scratch__inner_witness__leafbranch__field_descriptors,
  scratch__inner_witness__leafbranch__field_indices_by_name,
  1,  scratch__inner_witness__leafbranch__number_ranges,
  (ProtobufCMessageInit) scratch__inner_witness__leafbranch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scratch__inner_witness__field_descriptors[16] =
{
  {
    "root",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, root),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enc_key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, enc_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indshere",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, n_indshere),
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, indshere),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q1here",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, q1here),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lbhere",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, n_lbhere),
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, lbhere),
    &scratch__inner_witness__leafbranch__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_hmac",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, old_hmac),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_hmac",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, new_hmac),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cblocks",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, cblocks),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ciphertext",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, ciphertext),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_state",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, old_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_inds_state",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, old_inds_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_hmac_key",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, old_hmac_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_state",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, new_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_inds_state",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, new_inds_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hmac_key",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, hmac_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cnum",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__InnerWitness, cnum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scratch__inner_witness__field_indices_by_name[] = {
  7,   /* field[7] = cblocks */
  8,   /* field[8] = ciphertext */
  15,   /* field[15] = cnum */
  1,   /* field[1] = enc_key */
  14,   /* field[14] = hmac_key */
  2,   /* field[2] = indshere */
  4,   /* field[4] = lbhere */
  6,   /* field[6] = new_hmac */
  13,   /* field[13] = new_inds_state */
  12,   /* field[12] = new_state */
  5,   /* field[5] = old_hmac */
  11,   /* field[11] = old_hmac_key */
  10,   /* field[10] = old_inds_state */
  9,   /* field[9] = old_state */
  3,   /* field[3] = q1here */
  0,   /* field[0] = root */
};
static const ProtobufCIntRange scratch__inner_witness__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor scratch__inner_witness__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "scratch.InnerWitness",
  "InnerWitness",
  "Scratch__InnerWitness",
  "scratch",
  sizeof(Scratch__InnerWitness),
  16,
  scratch__inner_witness__field_descriptors,
  scratch__inner_witness__field_indices_by_name,
  1,  scratch__inner_witness__number_ranges,
  (ProtobufCMessageInit) scratch__inner_witness__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scratch__final_witness__field_descriptors[12] =
{
  {
    "root",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, root),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, nonce),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "first_hmac_key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, first_hmac_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h2",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, h2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inds_state_final",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, inds_state_final),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_hmac_key",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, last_hmac_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hmac0",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, hmac0),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hmacN",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, hmacn),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, message),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "puzstr",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, puzstr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secret_exponent",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, secret_exponent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secret_value",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Scratch__FinalWitness, secret_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scratch__final_witness__field_indices_by_name[] = {
  2,   /* field[2] = first_hmac_key */
  3,   /* field[3] = h2 */
  6,   /* field[6] = hmac0 */
  7,   /* field[7] = hmacN */
  4,   /* field[4] = inds_state_final */
  5,   /* field[5] = last_hmac_key */
  8,   /* field[8] = message */
  1,   /* field[1] = nonce */
  9,   /* field[9] = puzstr */
  0,   /* field[0] = root */
  10,   /* field[10] = secret_exponent */
  11,   /* field[11] = secret_value */
};
static const ProtobufCIntRange scratch__final_witness__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor scratch__final_witness__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "scratch.FinalWitness",
  "FinalWitness",
  "Scratch__FinalWitness",
  "scratch",
  sizeof(Scratch__FinalWitness),
  12,
  scratch__final_witness__field_descriptors,
  scratch__final_witness__field_indices_by_name,
  1,  scratch__final_witness__number_ranges,
  (ProtobufCMessageInit) scratch__final_witness__init,
  NULL,NULL,NULL    /* reserved[123] */
};
