/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_scratch_2eproto__INCLUDED
#define PROTOBUF_C_scratch_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Scratch__Puzzle Scratch__Puzzle;
typedef struct _Scratch__VerifierInput Scratch__VerifierInput;
typedef struct _Scratch__Ticket Scratch__Ticket;
typedef struct _Scratch__InnerWitness Scratch__InnerWitness;
typedef struct _Scratch__InnerWitness__Leafbranch Scratch__InnerWitness__Leafbranch;
typedef struct _Scratch__FinalWitness Scratch__FinalWitness;


/* --- enums --- */


/* --- messages --- */

struct  _Scratch__Puzzle
{
  ProtobufCMessage base;
  int32_t d;
  ProtobufCBinaryData puzid;
};
#define SCRATCH__PUZZLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scratch__puzzle__descriptor) \
    , 0, {0,NULL} }


struct  _Scratch__VerifierInput
{
  ProtobufCMessage base;
  ProtobufCBinaryData v_input;
};
#define SCRATCH__VERIFIER_INPUT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scratch__verifier_input__descriptor) \
    , {0,NULL} }


struct  _Scratch__Ticket
{
  ProtobufCMessage base;
  size_t n_ciphertexts;
  ProtobufCBinaryData *ciphertexts;
  size_t n_hmacs;
  ProtobufCBinaryData *hmacs;
  ProtobufCBinaryData public_value;
};
#define SCRATCH__TICKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scratch__ticket__descriptor) \
    , 0,NULL, 0,NULL, {0,NULL} }


struct  _Scratch__InnerWitness__Leafbranch
{
  ProtobufCMessage base;
  ProtobufCBinaryData leaf;
  size_t n_branch;
  ProtobufCBinaryData *branch;
};
#define SCRATCH__INNER_WITNESS__LEAFBRANCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scratch__inner_witness__leafbranch__descriptor) \
    , {0,NULL}, 0,NULL }


struct  _Scratch__InnerWitness
{
  ProtobufCMessage base;
  ProtobufCBinaryData root;
  ProtobufCBinaryData enc_key;
  size_t n_indshere;
  int32_t *indshere;
  int32_t q1here;
  size_t n_lbhere;
  Scratch__InnerWitness__Leafbranch **lbhere;
  ProtobufCBinaryData old_hmac;
  ProtobufCBinaryData new_hmac;
  ProtobufCBinaryData cblocks;
  ProtobufCBinaryData ciphertext;
  ProtobufCBinaryData old_state;
  ProtobufCBinaryData old_inds_state;
  ProtobufCBinaryData old_hmac_key;
  ProtobufCBinaryData new_state;
  ProtobufCBinaryData new_inds_state;
  ProtobufCBinaryData hmac_key;
  int32_t cnum;
};
#define SCRATCH__INNER_WITNESS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scratch__inner_witness__descriptor) \
    , {0,NULL}, {0,NULL}, 0,NULL, 0, 0,NULL, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, 0 }


struct  _Scratch__FinalWitness
{
  ProtobufCMessage base;
  ProtobufCBinaryData root;
  ProtobufCBinaryData nonce;
  ProtobufCBinaryData first_hmac_key;
  ProtobufCBinaryData h2;
  ProtobufCBinaryData inds_state_final;
  ProtobufCBinaryData last_hmac_key;
  ProtobufCBinaryData hmac0;
  ProtobufCBinaryData hmacn;
  ProtobufCBinaryData message;
  ProtobufCBinaryData puzstr;
  ProtobufCBinaryData secret_exponent;
  ProtobufCBinaryData secret_value;
};
#define SCRATCH__FINAL_WITNESS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scratch__final_witness__descriptor) \
    , {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL} }


/* Scratch__Puzzle methods */
void   scratch__puzzle__init
                     (Scratch__Puzzle         *message);
size_t scratch__puzzle__get_packed_size
                     (const Scratch__Puzzle   *message);
size_t scratch__puzzle__pack
                     (const Scratch__Puzzle   *message,
                      uint8_t             *out);
size_t scratch__puzzle__pack_to_buffer
                     (const Scratch__Puzzle   *message,
                      ProtobufCBuffer     *buffer);
Scratch__Puzzle *
       scratch__puzzle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scratch__puzzle__free_unpacked
                     (Scratch__Puzzle *message,
                      ProtobufCAllocator *allocator);
/* Scratch__VerifierInput methods */
void   scratch__verifier_input__init
                     (Scratch__VerifierInput         *message);
size_t scratch__verifier_input__get_packed_size
                     (const Scratch__VerifierInput   *message);
size_t scratch__verifier_input__pack
                     (const Scratch__VerifierInput   *message,
                      uint8_t             *out);
size_t scratch__verifier_input__pack_to_buffer
                     (const Scratch__VerifierInput   *message,
                      ProtobufCBuffer     *buffer);
Scratch__VerifierInput *
       scratch__verifier_input__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scratch__verifier_input__free_unpacked
                     (Scratch__VerifierInput *message,
                      ProtobufCAllocator *allocator);
/* Scratch__Ticket methods */
void   scratch__ticket__init
                     (Scratch__Ticket         *message);
size_t scratch__ticket__get_packed_size
                     (const Scratch__Ticket   *message);
size_t scratch__ticket__pack
                     (const Scratch__Ticket   *message,
                      uint8_t             *out);
size_t scratch__ticket__pack_to_buffer
                     (const Scratch__Ticket   *message,
                      ProtobufCBuffer     *buffer);
Scratch__Ticket *
       scratch__ticket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scratch__ticket__free_unpacked
                     (Scratch__Ticket *message,
                      ProtobufCAllocator *allocator);
/* Scratch__InnerWitness__Leafbranch methods */
void   scratch__inner_witness__leafbranch__init
                     (Scratch__InnerWitness__Leafbranch         *message);
/* Scratch__InnerWitness methods */
void   scratch__inner_witness__init
                     (Scratch__InnerWitness         *message);
size_t scratch__inner_witness__get_packed_size
                     (const Scratch__InnerWitness   *message);
size_t scratch__inner_witness__pack
                     (const Scratch__InnerWitness   *message,
                      uint8_t             *out);
size_t scratch__inner_witness__pack_to_buffer
                     (const Scratch__InnerWitness   *message,
                      ProtobufCBuffer     *buffer);
Scratch__InnerWitness *
       scratch__inner_witness__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scratch__inner_witness__free_unpacked
                     (Scratch__InnerWitness *message,
                      ProtobufCAllocator *allocator);
/* Scratch__FinalWitness methods */
void   scratch__final_witness__init
                     (Scratch__FinalWitness         *message);
size_t scratch__final_witness__get_packed_size
                     (const Scratch__FinalWitness   *message);
size_t scratch__final_witness__pack
                     (const Scratch__FinalWitness   *message,
                      uint8_t             *out);
size_t scratch__final_witness__pack_to_buffer
                     (const Scratch__FinalWitness   *message,
                      ProtobufCBuffer     *buffer);
Scratch__FinalWitness *
       scratch__final_witness__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scratch__final_witness__free_unpacked
                     (Scratch__FinalWitness *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Scratch__Puzzle_Closure)
                 (const Scratch__Puzzle *message,
                  void *closure_data);
typedef void (*Scratch__VerifierInput_Closure)
                 (const Scratch__VerifierInput *message,
                  void *closure_data);
typedef void (*Scratch__Ticket_Closure)
                 (const Scratch__Ticket *message,
                  void *closure_data);
typedef void (*Scratch__InnerWitness__Leafbranch_Closure)
                 (const Scratch__InnerWitness__Leafbranch *message,
                  void *closure_data);
typedef void (*Scratch__InnerWitness_Closure)
                 (const Scratch__InnerWitness *message,
                  void *closure_data);
typedef void (*Scratch__FinalWitness_Closure)
                 (const Scratch__FinalWitness *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor scratch__puzzle__descriptor;
extern const ProtobufCMessageDescriptor scratch__verifier_input__descriptor;
extern const ProtobufCMessageDescriptor scratch__ticket__descriptor;
extern const ProtobufCMessageDescriptor scratch__inner_witness__descriptor;
extern const ProtobufCMessageDescriptor scratch__inner_witness__leafbranch__descriptor;
extern const ProtobufCMessageDescriptor scratch__final_witness__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_scratch_2eproto__INCLUDED */
